---
title: "Tipologías de percepción: ¿Crisis democrática en Latinoamérica?"
format: html
editor: visual
bibliography: Crisis-democratica.bib
link-citations: true
---

## Introducción

A partir de la revuelta del 18 de octubre del año 2019 en Chile el debate respecto a los fenómenos políticos que vive la región y que permiten evaluar la condición de la democracia: populismo, distintos movimientos sociales, descontento y polarización política entre otros. Si bien no es una discusión que surge plenamente en este año, tuvo un auge respecto a la cantidad de análisis que intentaron explicar el fenómeno, evidenciando distintos elementos que podrían llegar a las causas de la revuelta.

En términos generales, las sociedades actuales y su nivel de complejidad se presentan como un objeto de estudio desafiante, y sin embargo, presenta similitudes en sus problemáticas respecto a las distintas naciones, la democracia como una de ellas. Un estudio realizado en el contexto de la Unión Europea constata de una situación relativamente generalizable: "La globalización tanto económica como de todas las instancias de poder se ha adueñado de los contextos que dominan la vida de las personas, originando cada día una brecha mayor entre la élite de la sociedad y el resto de los ciudadanos"[@juanantoniosanchezCRISISDEMOCRACIA2022]. Con este contexto general, podemos acercarnos el caso chileno.

Una de los análisis explora la posibilidad de que el causante del llamado estallido social de Chile tenga su explicación en la configuración de 4 crisis simultáneas: participación, representación, confianza y probidad [@mauriciomoralesquirogaEstallidoSocialChile2020].

Además, desde otro enfoque, es posible considerar aquellos elementos más estructurales; la presencia de enclaves autoritarios que estarían mermando la capacidad de la democracia, a la vez, que el desarrollo económico es insuficiente para disminuior las brechas sociales en la sociedad chilena, de forma que a pesar de las buenas condiciones económicas no resuelven los problemas distributivos de la nación [@nelsonalejandroosoriorauldQueSeVayan2019].

Tenemos entonces dos perspectivas que observan de distinta forma crisis estructurales, digamos, visiones desde arriba hacia abajo. Reforzando esto, podemos observar que existe una desafección política enraizada en un miedo hacia la política y un odio a la democracia a través de situaciones violentas como la dictadura, que finalmente predisponen a la ciudadanía contra la política [@cristobalfrizESTALLIDOSOCIALPOLITICA2021].

Esto nos acerca a la problemática central del estudio, enfocado en generar tipologías que permitan categorizar las distintas percepciones hacia la democracia, a partir de la encuesta Latinbarometro del año 2023. A partir de esta tipología exploratoria, se podría en primera instancia categorizar distintos perfiles de percepción con sus distintos niveles de cuestionamiento a la democracia. Para ello, se realizará un análisis de conglomerados, no tan solo para categorizar los perfiles, sino también para verificar su magnitud.

A partir de este procedimiento, se espera (1) encontrar al menos tres conglomerados distintos: a) buena percepción hacia la política y democracia, b) desinterés hacia la política y democracia, y c) mala percepción hacia la política y democracia. Además, se espera que (2) la mayor cantidad de casos se encuentre en la categoría C, esto según la literatura, que expresa una creciente desafección de la ciudadanía hacia la política y democracia debido a distintos elementos.
